package oygo

import "time"

type ScheduledDisbursementResult struct {
	Status             ScheduledDisbursementStatus `json:"status"`               //Status of Payout in Object {code: <status_code>, message: <status_message>}
	Amount             *float64                    `json:"amount"`               //Amount of disbursement (Accept Non-Decimal Number)
	RecipientBank      BankCode                    `json:"recipient_bank"`       //Bank Code of the Beneficiary account, see Disbursement Bank Codes
	RecipientAccount   string                      `json:"recipient_account"`    //Beneficiary account number
	PartnerTrxId       string                      `json:"partner_trx_id"`       //Unique Payout ID which partner put on the Request
	ScheduledTrxStatus string                      `json:"scheduled_trx_status"` //Status of scheduled disbursement
	ScheduleDate       string                      `json:"schedule_date"`        //Date for scheduled non-trigger-based disburse in "dd-mm-yyyy" format. Null if scheduled disbursement is trigger-based
	IsTriggerBased     bool                        `json:"is_trigger_based"`     //Whether scheduled transfer is trigger-based
	TriggerDate        string                      `json:"trigger_date"`         //Date when the disburse can be claimed by Beneficiary in "dd-mm-yyyy" format. Null if scheduled disbursement is non-trigger-based
	TriggerEmail       string                      `json:"trigger_email"`        //Email which the fund acceptance email and URL will be sent to. Null if scheduled disbursement is non-trigger-based
	Timestamp          *string                     `json:"timestamp"`            //Execution time of Disbursement in OY! system ("dd-MM-yyyy HH:mm:ss").
}

type ScheduledDisbursementStatus struct {
	Code    *string `json:"code"`
	Message *string `json:"message"`
}

type ScheduledDisbursementGet struct {
	Status              ScheduledDisbursementStatus `json:"status"`                //Status of Payout in Object {code: <status_code>, message: <status_message>}
	TxStatusDescription string                      `json:"tx_status_description"` //additional information of status code (e.g. FORCE CREDIT)
	Amount              float64                     `json:"amount"`                //Amount of disbursement (Accept Non-Decimal Number)
	RecipientName       string                      `json:"recipient_name"`        //Account holder name of Beneficiary account number
	RecipientBank       BankCode                    `json:"recipient_bank"`        //Bank Code of the Beneficiary account, see ScheduledDisbursement Bank Codes
	RecipientAccount    string                      `json:"recipient_account"`     //Beneficiary account number
	TrxId               string                      `json:"trx_id"`                //Unique Payout ID from OY!. Partner can use this ID for settlement
	PartnerTrxId        string                      `json:"partner_trx_id"`        //Unique Payout ID which partner put on the Request, generated by partner
	ScheduledTrxStatus  string                      `json:"scheduled_trx_status"`  //Status of scheduled disbursement
	ScheduleDate        string                      `json:"schedule_date"`         //Date for scheduled non-trigger-based disburse in "dd-mm-yyyy" format. Null if scheduled disbursement is trigger-based
	IsTriggerBased      bool                        `json:"is_trigger_based"`      //Whether scheduled transfer is trigger-based
	TriggerDate         string                      `json:"trigger_date"`          //Date when the disburse can be claimed by Beneficiary in "dd-mm-yyyy" format. Null if scheduled disbursement is non-trigger-based
	TriggerEmail        string                      `json:"trigger_email"`         //Email which the fund acceptance email and URL will be sent to. Null if scheduled disbursement is non-trigger-based
	Timestamp           time.Time                   `json:"timestamp"`             //Execution time of API remit status in OY! system ("dd-MM-yyyy HH:mm:ss")
}

type ScheduledDisbursementCallback struct {
	Status              ScheduledDisbursementStatus `json:"status" form:"status"`                               //Status of Payout in Object {code: <status_code>, message: <status_message>}
	TxStatusDescription string                      `json:"tx_status_description" form:"tx_status_description"` //additional information of status code (e.g. FORCE CREDIT)
	Amount              float64                     `json:"amount" form:"amount"`                               //Amount of disbursement (Accept Non-Decimal Number)
	RecipientName       string                      `json:"recipient_name" form:"recipient_name"`               //Account holder name of Beneficiary account number
	RecipientBank       BankCode                    `json:"recipient_bank" form:"recipient_bank"`               //Bank Code of the Beneficiary account, see ScheduledDisbursement Bank Codes
	RecipientAccount    string                      `json:"recipient_account" form:"recipient_account"`         //Beneficiary account number
	TrxId               string                      `json:"trx_id" form:"trx_id"`                               //Unique Payout ID from OY!. Partner can use this ID for settlement
	PartnerTrxId        string                      `json:"partner_trx_id" form:"partner_trx_id"`               //Unique Payout ID which partner put on the Request, generated by partner
	ScheduledTrxStatus  string                      `json:"scheduled_trx_status" form:"scheduled_trx_status"`   //Status of scheduled disbursement
	ScheduleDate        string                      `json:"schedule_date" form:"schedule_date"`                 //Date for scheduled non-trigger-based disburse in "dd-mm-yyyy" format. Null if scheduled disbursement is trigger-based
	IsTriggerBased      bool                        `json:"is_trigger_based" form:"is_trigger_based"`           //Whether scheduled transfer is trigger-based
	TriggerDate         string                      `json:"trigger_date" form:"trigger_date"`                   //Date when the disburse can be claimed by Beneficiary in "dd-mm-yyyy" format. Null if scheduled disbursement is non-trigger-based
	TriggerEmail        string                      `json:"trigger_email" form:"trigger_email"`                 //Email which the fund acceptance email and URL will be sent to. Null if scheduled disbursement is non-trigger-based
	Timestamp           string                      `json:"timestamp" form:"timestamp"`                         //Execution time of API remit status in OY! system ("dd-MM-yyyy HH:mm:ss")
	CreatedDate         string                      `json:"created_date" form:"created_date"`                   //Executionn time of Disbures in OY! system ("dd-MM-yyyy HH:mm:ss")
	LastUpdatedDate     string                      `json:"last_updated_date" form:"last_updated_date"`         //Latest status change of a disbursement. Example from 'Pending' to 'Success' ("dd-MM-yyyy HH:mm:ss")
}
