package disbursement

import oygo "github.com/nadhirfr/oy-go"

type CreateParams struct {
	RecipientBank    oygo.BankCode `json:"recipient_bank"`    //Bank Code of the Beneficiary account, see Disbursement Bank Codes
	RecipientAccount string        `json:"recipient_account"` //Beneficiary account number, numeric only
	Amount           int           `json:"amount"`            //Amount of disbursement (Accept Non-Decimal Number), min amount 10000
	Note             *string       `json:"note"`              //Add Note to the payout
	PartnerTrxId     *string       `json:"partner_trx_id"`    //Unique Payout ID for a specific request, generated by partner
	Email            string        `json:"email"`             //Email for invoice notification (Optional). Email can be more than one but not more that five separated by a whitespace.
}

// GetParams contains parameters for Get
type GetParams struct {
	PartnerTxId  string `json:"partner_tx_id" validate:"required"`
	SendCallback *bool  `json:"send_calback"`
}
